# Generated by Django 3.2.13 on 2023-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0004_auto_20230125_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressextension',
            name='BillToDistrict',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToDistrict',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
