# Generated by Django 3.2.13 on 2023-02-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0005_auto_20230201_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
