# Generated by Django 3.2.13 on 2023-02-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0007_quotation_paytermsgrpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='FreeText',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='UnitWeight',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='UomNo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
