# Generated by Django 3.2.13 on 2023-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0009_documentlines_taxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='FreeDelivery',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
    ]
