# Generated by Django 3.2.13 on 2023-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0010_quotation_freedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='CreatedBy',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
    ]
