# Generated by Django 3.2.13 on 2023-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0012_documentlines_unitpriceown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlines',
            name='UnitPriceown',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
