# Generated by Django 3.2.13 on 2023-02-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0012_item_u_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='UnitWeight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
