# Generated by Django 3.2.13 on 2023-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0013_item_unitweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='GSTTaxCategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
