# Generated by Django 4.0.3 on 2023-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0014_item_gsttaxcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoMList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AbsEntry', models.CharField(blank=True, max_length=10)),
                ('Code', models.CharField(blank=True, max_length=200)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('VolumeUnit', models.CharField(blank=True, max_length=200)),
                ('Weight1', models.CharField(blank=True, max_length=200)),
                ('Weight1Unit', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
