# Generated by Django 4.0.3 on 2023-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0015_uomlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='SalesItemsPerUnit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
