# Generated by Django 3.2.13 on 2023-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0017_item_uomids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(blank=True, max_length=200)),
                ('WarehouseCode', models.CharField(blank=True, max_length=200)),
                ('InStock', models.CharField(blank=True, max_length=200)),
                ('StandardAveragePrice', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
