# Generated by Django 3.2.19 on 2023-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0018_itemwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryId', models.IntegerField(default=0, unique=True)),
                ('SubCatName', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='U_UTL_ITMCT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='U_UTL_ITSBG',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='U_UTL_ST_ISSERVICE',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
