# Generated by Django 3.2.13 on 2023-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessPlaceID', models.CharField(blank=True, max_length=30)),
                ('Location', models.CharField(blank=True, max_length=30)),
                ('WarehouseCode', models.CharField(blank=True, max_length=50)),
                ('WarehouseName', models.CharField(blank=True, max_length=250)),
                ('Block', models.CharField(blank=True, max_length=250)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('City', models.CharField(blank=True, max_length=200)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('County', models.CharField(blank=True, max_length=100)),
                ('Street', models.CharField(blank=True, max_length=250)),
                ('ZipCode', models.CharField(blank=True, max_length=50)),
                ('Inactive', models.CharField(blank=True, max_length=30)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('UpdatedDate', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
