# Generated by Django 3.2.13 on 2023-01-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
