# Generated by Django 3.2.13 on 2023-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ACCNo',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='CompName',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='GST',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='Ifsc',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='U_LAT',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='U_LONG',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='Website',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
