# Generated by Django 3.2.13 on 2023-03-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_employee_vendercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='VenderCode',
        ),
    ]
