# Generated by Django 3.2.13 on 2023-04-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_auto_20230323_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='LocationSharing',
            field=models.CharField(blank=True, default='0', max_length=250),
        ),
    ]
