# Generated by Django 3.2.13 on 2023-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_employee_locationsharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Zone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
