# Generated by Django 3.2.13 on 2023-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0005_auto_20221216_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='customerType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='groupType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
