# Generated by Django 3.2.13 on 2023-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0006_auto_20230117_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartner',
            old_name='customerType',
            new_name='CustomerType',
        ),
        migrations.RenameField(
            model_name='businesspartner',
            old_name='groupType',
            new_name='DeliveryMode',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='GroupType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='PaymantMode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='PriceCategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='Turnover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
