# Generated by Django 3.2.13 on 2023-02-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0007_auto_20230120_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpaddresses',
            name='District',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bpbranch',
            name='District',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='ACNumber',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='BankName',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='BeneficiaryName',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='IfscCode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='TCS',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
