# Generated by Django 3.2.13 on 2023-02-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0008_auto_20230201_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartner',
            old_name='link',
            new_name='Link',
        ),
    ]
