# Generated by Django 3.2.13 on 2023-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0009_rename_link_businesspartner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='Unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
