# Generated by Django 3.2.13 on 2023-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0010_businesspartner_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='CreditLimitLeft',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='CreditLimit',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
