# Generated by Django 3.2.13 on 2023-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0011_auto_20230213_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='FreeDelivery',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
    ]
