# Generated by Django 4.0.3 on 2023-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0013_businesspartner_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='CreatedFromSap',
            field=models.CharField(blank=True, default=0, max_length=5),
        ),
    ]
