# Generated by Django 3.2.13 on 2023-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0015_auto_20230307_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=100)),
                ('Name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='GroupCode',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='U_U_UTL_DEPT',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='U_U_UTL_DIRC',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='U_U_UTL_EXEC',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='U_U_UTL_Zone',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
