# Generated by Django 3.2.13 on 2023-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0016_auto_20230418_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=250)),
                ('Name', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
