# Generated by Django 3.2.19 on 2023-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0017_businesspartnerzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='LinkedBusinessPartner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
