# Generated by Django 3.2.19 on 2023-06-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0018_businesspartner_linkedbusinesspartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpaddresses',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bpaddresses',
            name='GstType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
