# Generated by Django 3.2.19 on 2023-10-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0021_auto_20231018_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='BPAddresses',
            field=models.TextField(blank=True),
        ),
    ]
