# Generated by Django 3.2.19 on 2023-10-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0022_alter_receivable_bpaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='DocNum',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
