# Generated by Django 3.2.19 on 2023-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0023_receivable_docnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='CronUpdateCount',
            field=models.BigIntegerField(default=1),
        ),
    ]
