# Generated by Django 3.2.13 on 2023-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BPType', models.CharField(blank=True, max_length=200)),
                ('BPName', models.CharField(blank=True, max_length=200)),
                ('CardCode', models.CharField(blank=True, max_length=200)),
                ('SalesPersonCode', models.CharField(blank=True, max_length=200)),
                ('ModeOfTransport', models.CharField(blank=True, default='', max_length=200)),
                ('CheckInDate', models.CharField(blank=True, default='', max_length=200)),
                ('CheckInTime', models.CharField(blank=True, default='', max_length=200)),
                ('CheckInLat', models.CharField(blank=True, default='', max_length=200)),
                ('CheckInLong', models.CharField(blank=True, default='', max_length=200)),
                ('CheckInAttach', models.CharField(blank=True, default='', max_length=200)),
                ('CheckInRemarks', models.TextField(blank=True, default='')),
                ('CheckOutDate', models.CharField(blank=True, default='', max_length=200)),
                ('CheckOutTime', models.CharField(blank=True, default='', max_length=200)),
                ('CheckOutLat', models.CharField(blank=True, default='', max_length=200)),
                ('CheckOutLong', models.CharField(blank=True, default='', max_length=200)),
                ('CheckOutAttach', models.CharField(blank=True, default='', max_length=200)),
                ('CheckOutRemarks', models.TextField(blank=True, default='')),
                ('TotalDistanceAuto', models.CharField(blank=True, default='', max_length=200)),
                ('TotalDistanceManual', models.CharField(blank=True, default='', max_length=200)),
                ('TotalExpenses', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
