# Generated by Django 3.2.13 on 2023-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripExpenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpenses',
            name='CheckInStatus',
            field=models.CharField(blank=True, default='Start', max_length=100),
        ),
    ]
