# Generated by Django 3.2.13 on 2023-02-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0007_oppitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppitem',
            name='UnitWeight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
