# Generated by Django 3.2.13 on 2023-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0008_oppitem_unitweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='NGStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='ODStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='QTStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
