# Generated by Django 4.0.3 on 2023-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0011_alter_oppitem_unitpriceown'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='OppStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='oppitem',
            name='UnitPriceown',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
