# Generated by Django 3.2.19 on 2023-06-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0012_opportunity_oppstatus_alter_oppitem_unitpriceown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='OppStatus',
        ),
    ]
