# Generated by Django 3.2.19 on 2023-06-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0013_remove_opportunity_oppstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='OppStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
