# Generated by Django 3.2.13 on 2023-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountName', models.CharField(blank=True, max_length=200)),
                ('Type', models.CharField(blank=True, max_length=200)),
                ('SpecialInstr', models.CharField(blank=True, max_length=250)),
                ('Attach', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
