# Generated by Django 3.2.13 on 2023-05-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_auto_20230426_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tripId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
