# Generated by Django 3.2.19 on 2023-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='Comments',
            field=models.TextField(blank=True),
        ),
    ]
