# Generated by Django 3.2.13 on 2023-01-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_auto_20221209_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='leadType',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maps',
            name='ContactPerson',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='ResourceId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='SourceType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='remark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chatter',
            name='Mode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
