# Generated by Django 3.2.13 on 2023-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0007_auto_20230120_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='Attach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
