# Generated by Django 3.2.13 on 2023-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Series',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
