# Generated by Django 3.2.19 on 2023-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_branch_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=250)),
                ('Name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='FederalTaxID',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
