# Generated by Django 3.2.19 on 2023-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseInvoices', '0002_auto_20230711_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotesdocumentlines',
            name='BaseEntry',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnotesdocumentlines',
            name='ItemCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnotesdocumentlines',
            name='TaxCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnotesdocumentlines',
            name='TaxRate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='BaseEntry',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ItemCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ItemDescription',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='LineTotal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='TaxCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='TaxRate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='UomNo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='AdditionalCharges',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='CardCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='CardName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='ContactPersonCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='CreateDate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='CreateTime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='CreationDate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DeliveryCharge',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DiscountPercent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocCurrency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocDate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocDueDate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocEntry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocNum',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocTotal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='DocumentStatus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='InvoiceDocEntry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='OrderID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='SalesPersonCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='TaxDate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='UpdateDate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='UpdateTime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasecreditnotes',
            name='VatSum',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='AdditionalCharges',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='CardCode',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='ContactPersonCode',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='CreateDate',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='CreateTime',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='CreationDate',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DeliveryCharge',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DiscountPercent',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocCurrency',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocDate',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocDueDate',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocEntry',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocNum',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocTotal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='DocumentStatus',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='OrderID',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='SalesPersonCode',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='TaxDate',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='UpdateDate',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='UpdateTime',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='VatSum',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
