# Generated by Django 3.2.19 on 2024-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseInvoices', '0003_auto_20230815_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecreditnotes',
            name='PaidToDateSys',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseinvoices',
            name='PaidToDateSys',
            field=models.TextField(blank=True, default=0),
        ),
    ]
