# Generated by Django 3.2.19 on 2023-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntries', '0003_journalentries_u_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrylines',
            name='ReconSum',
            field=models.CharField(blank=True, default=0, max_length=250),
        ),
    ]
