# Generated by Django 3.2.13 on 2023-01-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0014_lead_junk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customerType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='projectAmount',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='stages',
            field=models.CharField(blank=True, default='New', max_length=100),
        ),
    ]
