# Generated by Django 3.2.13 on 2023-04-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0015_auto_20230117_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='U_LAT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='U_LONG',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
