# Generated by Django 3.2.19 on 2023-07-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressextension',
            name='BillToAddress2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='BillToAddress3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='BillToBlock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='BillToCounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='PlaceOfSupply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='PurchasePlaceOfSupply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToAddress2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToAddress3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToBlock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToCounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='Address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='Address2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='CGST',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='CNNo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='DocNum',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='GSTRate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='GSTTransactionType',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='IGST',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='NumAtCard',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='OriginalRefDate',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='OriginalRefNo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='RoundingDiffAmount',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='SGST',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_EWayBill',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_E_INV_Date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_SignedInvoice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_SignedQRCode',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_TransporterID',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_TransporterName',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_UNE_IRN',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_UNE_LRDate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_UNE_LRNo',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='U_VehicalNo',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='VATRegNum',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='BillToAddress2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='BillToAddress3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='BillToBlock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='BillToCounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='PlaceOfSupply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='PurchasePlaceOfSupply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='ShipToAddress2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='ShipToAddress3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='ShipToBlock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesaddressextension',
            name='ShipToCounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='HSN',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='HSNEntry',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='MeasureUnit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='SAC',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='SACEntry',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_RateType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_UTL_DD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_UTL_DIST',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_UTL_MRPI',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_UTL_SD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_UTL_SP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotesdocumentlines',
            name='U_UTL_TD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='HSN',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='HSNEntry',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='MeasureUnit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='SAC',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='SACEntry',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_RateType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_DD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_DIST',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_MRPI',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_SD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_SP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_TD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Address2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='CGST',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='CNNo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='DocNum',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='GSTRate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='GSTTransactionType',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='IGST',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='NumAtCard',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='OriginalRefDate',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='OriginalRefNo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='RoundingDiffAmount',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='SGST',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_EWayBill',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_E_INV_Date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_SignedInvoice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_SignedQRCode',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_TransporterID',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_TransporterName',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_UNE_IRN',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_UNE_LRDate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_UNE_LRNo',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='U_VehicalNo',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='VATRegNum',
            field=models.TextField(blank=True, default=''),
        ),
    ]
