# Generated by Django 3.2.19 on 2023-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_auto_20230802_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='U_UTL_ITSBG',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
