# Generated by Django 3.2.19 on 2023-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_documentlines_u_utl_itsbg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlines',
            name='ItemDescription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
